"project_id": "203839"
"api_token_env": "${CROWDIN_PERSONAL_TOKEN}"
"base_path": ""
"preserve_hierarchy": true

"files": [
  {
    "source": "app/src/main/res/values/strings.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/strings.xml",
    "dest": "base.xml"
  },
  {
    "source": "app/src/main/res/values/about.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/about.xml",
    "dest": "about.xml"
  },
  {
    "source": "app/src/main/res/values/calendar.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/calendar.xml",
    "dest": "calendar.xml"
  },
  {
    "source": "app/src/main/res/values/compass.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/compass.xml",
    "dest": "compass.xml"
  },
  {
    "source": "app/src/main/res/values/dhikr.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/dhikr.xml",
    "dest": "dhikr.xml"
  },
  {
    "source": "app/src/main/res/values/hadith.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/hadith.xml",
    "dest": "hadith.xml"
  },
  {
    "source": "app/src/main/res/values/intro.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/intro.xml",
    "dest": "intro.xml"
  },
  {
    "source": "app/src/main/res/values/missedprayers.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/missedprayers.xml",
    "dest": "missedprayers.xml"
  },
  {
    "source": "app/src/main/res/values/settings.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/settings.xml",
    "dest": "settings.xml"
  },
  {
    "source": "app/src/main/res/values/tesbihat.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/tesbihat.xml",
    "dest": "tesbihat.xml"
  },
  {
    "source": "app/src/main/res/values/times.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/times.xml",
    "dest": "times.xml"
  },
  {
    "source": "app/src/main/res/values/widget.xml",
    "translation": "app/src/main/translations/values-%two_letters_code%/widget.xml",
    "dest": "widget.xml"
  }
]







